In [1]:
# Machine Learning Analysis and Classification of Attacks using Botnet Dataset

In [2]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report

from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')

In [3]:
# Training Dataset
data = pd.read_csv("UNSW_2018_IoT_Botnet_Final_10_best_Training.csv")
data.head()

pkSeqID proto            saddr  sport          daddr dport     seq  \
0  3142762   udp  192.168.100.150   6551  192.168.100.3    80  251984   
1  2432264   tcp  192.168.100.150   5532  192.168.100.3    80  256724   
2  1976315   tcp  192.168.100.147  27165  192.168.100.3    80   62921   
3  1240757   udp  192.168.100.150  48719  192.168.100.3    80   99168   
4  3257991   udp  192.168.100.147  22461  192.168.100.3    80  105063   

     stddev  N_IN_Conn_P_SrcIP       min  state_number      mean  \
0  1.900363                100  0.000000             4  2.687519   
1  0.078003                 38  3.856930             3  3.934927   
2  0.268666                100  2.974100             3  3.341429   
3  1.823185                 63  0.000000             4  3.222832   
4  0.822418                100  2.979995             4  3.983222   

   N_IN_Conn_P_DstIP  drate     srate       max  attack category subcategory  
0                100    0.0  0.494549  4.031619       1     DDoS         UDP  
1                100    0.0  0.256493  4.012924       1     DDoS         TCP  
2                100    0.0  0.294880  3.609205       1     DDoS         TCP  
3                 63    0.0  0.461435  4.942302       1      DoS         UDP  
4                100    0.0  1.002999  4.994452       1     DDoS         UDP

In [4]:
# General Information about the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2934817 entries, 0 to 2934816
Data columns (total 19 columns):
 #   Column             Dtype  
---  ------             -----  
 0   pkSeqID            int64  
 1   proto              object 
 2   saddr              object 
 3   sport              object 
 4   daddr              object 
 5   dport              object 
 6   seq                int64  
 7   stddev             float64
 8   N_IN_Conn_P_SrcIP  int64  
 9   min                float64
 10  state_number       int64  
 11  mean               float64
 12  N_IN_Conn_P_DstIP  int64  
 13  drate              float64
 14  srate              float64
 15  max                float64
 16  attack             int64  
 17  category           object 
 18  subcategory        object 
dtypes: float64(6), int64(6), object(7)
memory usage: 425.4+ MB


In [5]:
data.describe()

pkSeqID           seq        stddev  N_IN_Conn_P_SrcIP  \
count  2.934817e+06  2.934817e+06  2.934817e+06       2.934817e+06   
mean   1.834209e+06  1.212973e+05  8.869639e-01       8.254997e+01   
std    1.059058e+06  7.578700e+04  8.036391e-01       2.439019e+01   
min    1.000000e+00  1.000000e+00  0.000000e+00       1.000000e+00   
25%    9.171090e+05  5.484700e+04  2.999700e-02       6.900000e+01   
50%    1.834316e+06  1.177370e+05  7.925750e-01       1.000000e+02   
75%    2.751250e+06  1.848700e+05  1.745220e+00       1.000000e+02   
max    3.668522e+06  2.622110e+05  2.496763e+00       1.000000e+02   

                min  state_number          mean  N_IN_Conn_P_DstIP  \
count  2.934817e+06  2.934817e+06  2.934817e+06       2.934817e+06   
mean   1.017208e+00  3.134219e+00  2.230471e+00       9.245766e+01   
std    1.483551e+00  1.187107e+00  1.517766e+00       1.816651e+01   
min    0.000000e+00  1.000000e+00  0.000000e+00       1.000000e+00   
25%    0.000000e+00  3.000000e+00  1.819340e-01       1.000000e+02   
50%    0.000000e+00  4.000000e+00  2.689973e+00       1.000000e+02   
75%    2.147949e+00  4.000000e+00  3.565061e+00       1.000000e+02   
max    4.980471e+00  1.100000e+01  4.981882e+00       1.000000e+02   

              drate         srate           max        attack  
count  2.934817e+06  2.934817e+06  2.934817e+06  2.934817e+06  
mean   4.303064e-01  3.128290e+00  3.019269e+00  9.998739e-01  
std    5.623304e+01  7.845494e+02  1.860915e+00  1.122750e-02  
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
25%    0.000000e+00  1.558450e-01  2.804170e-01  1.000000e+00  
50%    0.000000e+00  2.837800e-01  4.008429e+00  1.000000e+00  
75%    0.000000e+00  4.880000e-01  4.292426e+00  1.000000e+00  
max    5.882353e+04  1.000000e+06  4.999999e+00  1.000000e+00

In [6]:
data.proto.value_counts()

udp          1596819
tcp          1330598
icmp            7228
arp              166
ipv6-icmp          6
Name: proto, dtype: int64

In [7]:
data.saddr.value_counts()

192.168.100.147              761360
192.168.100.148              738642
192.168.100.150              712260
192.168.100.149              711466
192.168.100.3                  6609
192.168.100.5                  4107
192.168.100.6                   272
192.168.100.7                    34
192.168.100.4                    17
192.168.100.1                    14
192.168.100.27                    9
192.168.100.46                    8
fe80::250:56ff:febe:254           5
192.168.100.55                    3
fe80::2c6a:ff9b:7e14:166a         2
fe80::250:56ff:febe:26db          2
fe80::c0c0:aa20:45b9:bdd9         2
fe80::250:56ff:febe:89ee          2
fe80::250:56ff:febe:c038          2
fe80::250:56ff:febe:e9d9          1
Name: saddr, dtype: int64

In [8]:
data.daddr.value_counts()

192.168.100.3      1900562
192.168.100.5       361192
192.168.100.7       332161
192.168.100.6       329679
192.168.100.150       3040
                    ...   
205.251.194.167          1
205.251.199.61           1
205.251.196.160          1
216.239.36.10            1
184.85.248.65            1
Name: daddr, Length: 81, dtype: int64

In [9]:
data.sport.value_counts()

0x0303    7156
80        3220
1822       878
60541      869
1216       868
          ... 
32047       31
39305       30
18992       30
0x000d      10
0x0011       8
Name: sport, Length: 65541, dtype: int64

In [10]:
data.dport.value_counts()

80       2858794
1           5379
3306        3757
53           275
-1           166
          ...   
8293           1
7510           1
25593          1
65151          1
6473           1
Name: dport, Length: 6906, dtype: int64

In [11]:
data.category.value_counts()

DDoS              1541315
DoS               1320148
Reconnaissance      72919
Normal                370
Theft                  65
Name: category, dtype: int64

In [12]:
data.attack.value_counts()

1    2934447
0        370
Name: attack, dtype: int64

In [13]:
data.subcategory.value_counts()

UDP                  1584650
TCP                  1274843
Service_Scan           58626
OS_Fingerprint         14293
HTTP                    1970
Normal                   370
Keylogging                59
Data_Exfiltration          6
Name: subcategory, dtype: int64

In [14]:
# Extracting 10 best features

In [15]:
ten_best_features = data[['seq','stddev','N_IN_Conn_P_SrcIP', 'min', 'state_number', 'mean', 'N_IN_Conn_P_DstIP',
       'drate', 'srate', 'max']]
target_features = data[['attack','category','subcategory']]

In [16]:
# Data Preprocessing

In [17]:
# Label Encoding the target columns
le = LabelEncoder()
target_features['category'] = le.fit_transform(target_features['category'])
target_features['subcategory'] = le.fit_transform(target_features['subcategory'])

target_features.head()

attack  category  subcategory
0       1         0            7
1       1         0            6
2       1         0            6
3       1         1            7
4       1         0            7

In [18]:
# Train-test Split
X_train, X_test, y_train, y_test = train_test_split(ten_best_features,target_features)

In [19]:
# Scaling the data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
# Defining the ML Model Classes

In [21]:
class RandomForest:
    def __init__(self,max_depth):
        self.rfc_attack = RandomForestClassifier(max_depth=max_depth)
        self.rfc_category = RandomForestClassifier(max_depth=max_depth)
        self.rfc_subcategory = RandomForestClassifier(max_depth=max_depth)
    
    def fit(self,X_train,y_train):
        self.rfc_attack.fit(X_train,y_train['attack'])
        
        features_category = np.concatenate((X_train,np.array(y_train['attack']).reshape(-1,1)),axis=1)
        self.rfc_category.fit(features_category,y_train['category'])
        
        features_subcategory = np.concatenate((features_category,np.array(y_train['category']).reshape(-1,1)),axis=1)
        self.rfc_subcategory.fit(features_subcategory,y_train['subcategory'])
        
    def predict(self,X_test):
        predict_attack = self.rfc_attack.predict(X_test)
        
        test_category = np.concatenate((X_test,predict_attack.reshape(-1,1)),axis=1)
        predict_category = self.rfc_category.predict(test_category)
        
        test_subcategory = np.concatenate((test_category,predict_category.reshape(-1,1)),axis=1)
        predict_subcategory = self.rfc_subcategory.predict(test_subcategory)
        
        return pd.DataFrame({'attack':predict_attack,'category':predict_category,'subcategory':predict_subcategory})

In [22]:
class NaiveBayes:
    def __init__(self):
        self.nb_attack = GaussianNB()
        self.nb_category = GaussianNB()
        self.nb_subcategory = GaussianNB()
    
    def fit(self,X_train,y_train):
        self.nb_attack.fit(X_train,y_train['attack'])
        
        features_category = np.concatenate((X_train,np.array(y_train['attack']).reshape(-1,1)),axis=1)
        self.nb_category.fit(features_category,y_train['category'])
        
        features_subcategory = np.concatenate((features_category,np.array(y_train['category']).reshape(-1,1)),axis=1)
        self.nb_subcategory.fit(features_subcategory,y_train['subcategory'])
        
    def predict(self,X_test):
        predict_attack = self.nb_attack.predict(X_test)
        
        test_category = np.concatenate((X_test,predict_attack.reshape(-1,1)),axis=1)
        predict_category = self.nb_category.predict(test_category)
        
        test_subcategory = np.concatenate((test_category,predict_category.reshape(-1,1)),axis=1)
        predict_subcategory = self.nb_subcategory.predict(test_subcategory)
        
        return pd.DataFrame({'attack':predict_attack,'category':predict_category,'subcategory':predict_subcategory})

In [23]:
class DecisionTree:
    def __init__(self,criterion,max_depth=5):
        self.dtree_attack = DecisionTreeClassifier(criterion=criterion,max_depth=max_depth)
        self.dtree_category = DecisionTreeClassifier(criterion=criterion,max_depth=max_depth)
        self.dtree_subcategory = DecisionTreeClassifier(criterion=criterion,max_depth=max_depth)
    
    def fit(self,X_train,y_train):
        self.dtree_attack.fit(X_train,y_train['attack'])
        
        features_category = np.concatenate((X_train,np.array(y_train['attack']).reshape(-1,1)),axis=1)
        self.dtree_category.fit(features_category,y_train['category'])
        
        features_subcategory = np.concatenate((features_category,np.array(y_train['category']).reshape(-1,1)),axis=1)
        self.dtree_subcategory.fit(features_subcategory,y_train['subcategory'])
        
    def predict(self,X_test):
        predict_attack = self.dtree_attack.predict(X_test)
        
        test_category = np.concatenate((X_test,predict_attack.reshape(-1,1)),axis=1)
        predict_category = self.dtree_category.predict(test_category)
        
        test_subcategory = np.concatenate((test_category,predict_category.reshape(-1,1)),axis=1)
        predict_subcategory = self.dtree_subcategory.predict(test_subcategory)
        
        return pd.DataFrame({'attack':predict_attack,'category':predict_category,'subcategory':predict_subcategory})

In [24]:
class GradientBoost:
    def __init__(self):
        self.xgb_attack = XGBClassifier()
        self.xgb_category = XGBClassifier()
        self.xgb_subcategory = XGBClassifier()
    
    def fit(self,X_train,y_train):
        self.xgb_attack.fit(X_train,y_train['attack'])
        
        features_category = np.concatenate((X_train,np.array(y_train['attack']).reshape(-1,1)),axis=1)
        self.xgb_category.fit(features_category,y_train['category'])
        
        features_subcategory = np.concatenate((features_category,np.array(y_train['category']).reshape(-1,1)),axis=1)
        self.xgb_subcategory.fit(features_subcategory,y_train['subcategory'])
        
    def predict(self,X_test):
        predict_attack = self.xgb_attack.predict(X_test)
        
        test_category = np.concatenate((X_test,predict_attack.reshape(-1,1)),axis=1)
        predict_category = self.xgb_category.predict(test_category)
        
        test_subcategory = np.concatenate((test_category,predict_category.reshape(-1,1)),axis=1)
        predict_subcategory = self.xgb_subcategory.predict(test_subcategory)
        
        return pd.DataFrame({'attack':predict_attack,'category':predict_category,'subcategory':predict_subcategory})

In [25]:
# Validation of ML Models on Training Dataset

In [26]:
# Random Forest

rf = RandomForest(max_depth=3)
rf.fit(X_train,y_train)

predictions_rfc = rf.predict(X_test)

In [27]:
print(confusion_matrix(y_test['attack'],predictions_rfc['attack']))
print(classification_report(y_test['attack'],predictions_rfc['attack']))

[[     5     96]
 [     0 733604]]
              precision    recall  f1-score   support

           0       1.00      0.05      0.09       101
           1       1.00      1.00      1.00    733604

    accuracy                           1.00    733705
   macro avg       1.00      0.52      0.55    733705
weighted avg       1.00      1.00      1.00    733705



In [28]:
print(confusion_matrix(y_test['subcategory'],predictions_rfc['subcategory']))
print(classification_report(y_test['subcategory'],predictions_rfc['subcategory']))

[[     0      0      0      0      0      0      0      1]
 [     0      0      0      0      0      2    492      0]
 [     0      0      0      0      0      5      0      4]
 [     0      0      0      0      0     10     85      6]
 [     0      0      0      0      0    139   3428      6]
 [     0      0      0      0      0   5883   8794      4]
 [     0      0      0      0      0      1 318377    198]
 [     0      0      0      0      0      0      7 396263]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00       494
           2       0.00      0.00      0.00         9
           3       0.00      0.00      0.00       101
           4       0.00      0.00      0.00      3573
           5       0.97      0.40      0.57     14681
           6       0.96      1.00      0.98    318576
           7       1.00      1.00      1.00    396270

    accuracy                           

In [29]:
print(confusion_matrix(y_test['category'],predictions_rfc['category']))
print(classification_report(y_test['category'],predictions_rfc['category']))

[[365896  18907      0      0      0]
 [ 35865 294669      0      3      0]
 [     1     91      0      9      0]
 [ 11208   2631      0   4415      0]
 [     0      5      0      5      0]]
              precision    recall  f1-score   support

           0       0.89      0.95      0.92    384803
           1       0.93      0.89      0.91    330537
           2       0.00      0.00      0.00       101
           3       1.00      0.24      0.39     18254
           4       0.00      0.00      0.00        10

    accuracy                           0.91    733705
   macro avg       0.56      0.42      0.44    733705
weighted avg       0.91      0.91      0.90    733705



In [30]:
print(confusion_matrix(y_test['subcategory'],predictions_rfc['subcategory']))
print(classification_report(y_test['subcategory'],predictions_rfc['subcategory']))

[[     0      0      0      0      0      0      0      1]
 [     0      0      0      0      0      2    492      0]
 [     0      0      0      0      0      5      0      4]
 [     0      0      0      0      0     10     85      6]
 [     0      0      0      0      0    139   3428      6]
 [     0      0      0      0      0   5883   8794      4]
 [     0      0      0      0      0      1 318377    198]
 [     0      0      0      0      0      0      7 396263]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00       494
           2       0.00      0.00      0.00         9
           3       0.00      0.00      0.00       101
           4       0.00      0.00      0.00      3573
           5       0.97      0.40      0.57     14681
           6       0.96      1.00      0.98    318576
           7       1.00      1.00      1.00    396270

    accuracy                           

In [31]:
rf.rfc_attack.score(X_test,y_test['attack'])

0.9998691572225895

In [32]:
rf.rfc_category.score(np.concatenate((X_test,np.array(predictions_rfc['attack']).reshape(-1,1)),axis=1),y_test['category'])

0.9063315637756318

In [33]:
rf.rfc_subcategory.score(np.concatenate((X_test,np.array(predictions_rfc['attack']).reshape(-1,1),
                                    np.array(predictions_rfc['category']).reshape(-1,1)),axis=1),y_test['subcategory'])

0.9820336511268153

In [34]:
# Naive Bayes

In [35]:
nb = NaiveBayes()
nb.fit(X_train,y_train)

predictions_nb = nb.predict(X_test)

In [36]:
print(confusion_matrix(y_test['attack'],predictions_nb['attack']))
print(classification_report(y_test['attack'],predictions_nb['attack']))

[[    95      6]
 [  2751 730853]]
              precision    recall  f1-score   support

           0       0.03      0.94      0.06       101
           1       1.00      1.00      1.00    733604

    accuracy                           1.00    733705
   macro avg       0.52      0.97      0.53    733705
weighted avg       1.00      1.00      1.00    733705



In [37]:
print(confusion_matrix(y_test['category'],predictions_nb['category']))
print(classification_report(y_test['category'],predictions_nb['category']))

[[368232  16440     38     93      0]
 [183310 146265    658    304      0]
 [     0      4     95      2      0]
 [ 10693   2571   2049   2941      0]
 [     0      0      6      0      4]]
              precision    recall  f1-score   support

           0       0.65      0.96      0.78    384803
           1       0.88      0.44      0.59    330537
           2       0.03      0.94      0.06       101
           3       0.88      0.16      0.27     18254
           4       1.00      0.40      0.57        10

    accuracy                           0.71    733705
   macro avg       0.69      0.58      0.46    733705
weighted avg       0.76      0.71      0.68    733705



In [38]:
print(confusion_matrix(y_test['subcategory'],predictions_nb['subcategory']))
print(classification_report(y_test['subcategory'],predictions_nb['subcategory']))

[[     0      0      0      1      0      0      0      0]
 [     0    334      0      9      9    130     12      0]
 [     2      0      2      5      0      0      0      0]
 [     0      1      0     95      1      1      3      0]
 [     0    213      0    103      4    121   3132      0]
 [     0    527      0   1946    684   2132   9392      0]
 [     0    818      0    677      6    251 316824      0]
 [     0      0      0     10      1      0     21 396238]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.18      0.68      0.28       494
           2       1.00      0.22      0.36         9
           3       0.03      0.94      0.06       101
           4       0.01      0.00      0.00      3573
           5       0.81      0.15      0.25     14681
           6       0.96      0.99      0.98    318576
           7       1.00      1.00      1.00    396270

    accuracy                           

In [39]:
# Decision Tree (Information Gain)

In [40]:
dtree_ig = DecisionTree('entropy')
dtree_ig.fit(X_train,y_train)
predictions_dtree_ig = dtree_ig.predict(X_test)

In [41]:
print(confusion_matrix(y_test['attack'],predictions_dtree_ig['attack']))
print(classification_report(y_test['attack'],predictions_dtree_ig['attack']))

[[    38     63]
 [     6 733598]]
              precision    recall  f1-score   support

           0       0.86      0.38      0.52       101
           1       1.00      1.00      1.00    733604

    accuracy                           1.00    733705
   macro avg       0.93      0.69      0.76    733705
weighted avg       1.00      1.00      1.00    733705



In [42]:
print(confusion_matrix(y_test['category'],predictions_dtree_ig['category']))
print(classification_report(y_test['category'],predictions_dtree_ig['category']))

[[338499  45737      0    567      0]
 [ 11718 318780      1     38      0]
 [     3     21     31     46      0]
 [   378   7428      2  10446      0]
 [     0      0      0     10      0]]
              precision    recall  f1-score   support

           0       0.97      0.88      0.92    384803
           1       0.86      0.96      0.91    330537
           2       0.91      0.31      0.46       101
           3       0.94      0.57      0.71     18254
           4       0.00      0.00      0.00        10

    accuracy                           0.91    733705
   macro avg       0.73      0.54      0.60    733705
weighted avg       0.92      0.91      0.91    733705



In [43]:
print(confusion_matrix(y_test['subcategory'],predictions_dtree_ig['subcategory']))
print(classification_report(y_test['subcategory'],predictions_dtree_ig['subcategory']))

[[     0      0      1      0      0      0      0      0]
 [     0    353      0      1      0     90     50      0]
 [     0      0      4      0      0      5      0      0]
 [     0      0      0     33      6     37      5     20]
 [     0      0      0      4    916    546   2083     24]
 [     0     18      0      0    224   8760   5665     14]
 [     0      1      0      0      1    495 318077      2]
 [     0      0      0      0      0      0      2 396268]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.95      0.71      0.82       494
           2       0.80      0.44      0.57         9
           3       0.87      0.33      0.47       101
           4       0.80      0.26      0.39      3573
           5       0.88      0.60      0.71     14681
           6       0.98      1.00      0.99    318576
           7       1.00      1.00      1.00    396270

    accuracy                           

In [44]:
dtree_ig.dtree_attack.score(X_test,y_test['attack'])

0.9999059567537362

In [45]:
dtree_ig.dtree_category.score(np.concatenate((X_test,np.array(predictions_dtree_ig['attack']).reshape(-1,1)),axis=1),y_test['category'])

0.9101151007557533

In [46]:
dtree_ig.dtree_subcategory.score(np.concatenate((X_test,np.array(predictions_dtree_ig['attack']).reshape(-1,1),
                                        np.array(predictions_dtree_ig['category']).reshape(-1,1)),axis=1),y_test['subcategory'])

0.9873327836119421

In [47]:
# Gradient Boost

In [48]:
xgb = GradientBoost()
xgb.fit(X_train,y_train)
predictions_xgb = xgb.predict(X_test)

[13:49:30] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[13:50:41] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[13:56:17] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [49]:
print(confusion_matrix(y_test['attack'],predictions_xgb['attack']))
print(classification_report(y_test['attack'],predictions_xgb['attack']))

[[    98      3]
 [     1 733603]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       101
           1       1.00      1.00      1.00    733604

    accuracy                           1.00    733705
   macro avg       0.99      0.99      0.99    733705
weighted avg       1.00      1.00      1.00    733705



In [50]:
print(confusion_matrix(y_test['category'],predictions_xgb['category']))
print(classification_report(y_test['category'],predictions_xgb['category']))

[[384776     27      0      0      0]
 [    18 330518      0      1      0]
 [     0      3     98      0      0]
 [     0      0      1  18252      1]
 [     0      0      0      0     10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    384803
           1       1.00      1.00      1.00    330537
           2       0.99      0.97      0.98       101
           3       1.00      1.00      1.00     18254
           4       0.91      1.00      0.95        10

    accuracy                           1.00    733705
   macro avg       0.98      0.99      0.99    733705
weighted avg       1.00      1.00      1.00    733705



In [51]:
print(confusion_matrix(y_test['subcategory'],predictions_xgb['subcategory']))
print(classification_report(y_test['subcategory'],predictions_xgb['subcategory']))

[[     1      0      0      0      0      0      0      0]
 [     0    491      0      0      1      0      2      0]
 [     0      0      9      0      0      0      0      0]
 [     0      1      0     98      0      0      1      1]
 [     0      0      0      1   3336    236      0      0]
 [     0      0      1      0    216  14464      0      0]
 [     0      0      0      0      0      0 318575      1]
 [     0      0      0      0      0      0      1 396269]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      0.99      1.00       494
           2       0.90      1.00      0.95         9
           3       0.99      0.97      0.98       101
           4       0.94      0.93      0.94      3573
           5       0.98      0.99      0.98     14681
           6       1.00      1.00      1.00    318576
           7       1.00      1.00      1.00    396270

    accuracy                           

In [52]:
xgb.xgb_attack.score(X_test,y_test['attack'])

0.9999945482176079

In [53]:
xgb.xgb_subcategory.score(np.concatenate((X_test,np.array(predictions_xgb['attack']).reshape(-1,1),
                                        np.array(predictions_xgb['category']).reshape(-1,1)),axis=1),y_test['subcategory'])

0.9993703191337118

In [54]:
# Test Data

In [55]:
test_data = pd.read_csv("UNSW_2018_IoT_Botnet_Final_10_best_Testing.csv")
test_data.head()

pkSeqID proto            saddr  sport          daddr dport     seq  \
0   792371   udp  192.168.100.150  48516  192.168.100.3    80  175094   
1  2056418   tcp  192.168.100.148  22267  192.168.100.3    80  143024   
2  2795650   udp  192.168.100.149  28629  192.168.100.3    80  167033   
3  2118009   tcp  192.168.100.148  42142  192.168.100.3    80  204615   
4   303688   tcp  192.168.100.149   1645  192.168.100.5    80   40058   

     stddev  N_IN_Conn_P_SrcIP       min  state_number      mean  \
0  0.226784                100  4.100436             4  4.457383   
1  0.451998                100  3.439257             1  3.806172   
2  1.931553                 73  0.000000             4  2.731204   
3  0.428798                 56  3.271411             1  3.626428   
4  2.058381                100  0.000000             3  1.188407   

   N_IN_Conn_P_DstIP     drate     srate       max  attack category  \
0                100  0.000000  0.404711  4.719438       1      DoS   
1                100  0.225077  0.401397  4.442930       1     DDoS   
2                100  0.000000  0.407287  4.138455       1     DDoS   
3                100  0.000000  0.343654  4.229700       1     DDoS   
4                100  0.000000  0.135842  4.753628       1      DoS   

  subcategory  
0         UDP  
1         TCP  
2         UDP  
3         TCP  
4         TCP

In [56]:
# Extracting the ten-best features from test set
test_ten_best = test_data[ten_best_features.columns]
test_labels = test_data[['attack','category','subcategory']]
test_ten_best.head()

seq    stddev  N_IN_Conn_P_SrcIP       min  state_number      mean  \
0  175094  0.226784                100  4.100436             4  4.457383   
1  143024  0.451998                100  3.439257             1  3.806172   
2  167033  1.931553                 73  0.000000             4  2.731204   
3  204615  0.428798                 56  3.271411             1  3.626428   
4   40058  2.058381                100  0.000000             3  1.188407   

   N_IN_Conn_P_DstIP     drate     srate       max  
0                100  0.000000  0.404711  4.719438  
1                100  0.225077  0.401397  4.442930  
2                100  0.000000  0.407287  4.138455  
3                100  0.000000  0.343654  4.229700  
4                100  0.000000  0.135842  4.753628

In [57]:
# Standard Scaling
train_data = sc.fit_transform(ten_best_features)
test = sc.transform(test_ten_best)

In [58]:
ten_best_features = data[['seq','stddev','N_IN_Conn_P_SrcIP', 'min', 'state_number', 'mean', 'N_IN_Conn_P_DstIP',
       'drate', 'srate', 'max']]
target_features = data[['attack','category','subcategory']]

In [59]:
# Label Encoding

target_features['category'] = le.fit_transform(target_features['category'])
test_labels['category'] = le.transform(test_labels['category'])

target_features['subcategory'] = le.fit_transform(target_features['subcategory'])
test_labels['subcategory'] = le.transform(test_labels['subcategory'])

In [60]:
# Training ML Models on Complete Data and Testing on test set

In [61]:
# Random Forest
rf_clf = RandomForest(max_depth=3)
rf_clf.fit(train_data,target_features)
predictions_rf = rf_clf.predict(test)

In [62]:
print("Random Forest: Attack\n")
print(confusion_matrix(test_labels['attack'],predictions_rf['attack']),"\n")
print(classification_report(test_labels['attack'],predictions_rf['attack']))

Random Forest: Attack

[[     9     98]
 [     0 733598]] 

              precision    recall  f1-score   support

           0       1.00      0.08      0.16       107
           1       1.00      1.00      1.00    733598

    accuracy                           1.00    733705
   macro avg       1.00      0.54      0.58    733705
weighted avg       1.00      1.00      1.00    733705



In [63]:
print("Random Forest: Category\n")
print(confusion_matrix(test_labels['category'],predictions_rf['category']))
print(classification_report(test_labels['category'],predictions_rf['category']))

Random Forest: Category

[[371598  13711      0      0      0]
 [ 37390 292721      0      1      0]
 [     0     95      0     12      0]
 [ 10189   2737      0   5237      0]
 [     0      5      0      9      0]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92    385309
           1       0.95      0.89      0.92    330112
           2       0.00      0.00      0.00       107
           3       1.00      0.29      0.45     18163
           4       0.00      0.00      0.00        14

    accuracy                           0.91    733705
   macro avg       0.57      0.43      0.46    733705
weighted avg       0.92      0.91      0.91    733705



In [64]:
print("Random Forest: Subcategory\n")
print(confusion_matrix(test_labels['subcategory'],predictions_rf['subcategory']))
print(classification_report(test_labels['subcategory'],predictions_rf['subcategory']))

Random Forest: Subcategory

[[     0      0      0      0      1    503      0]
 [     0      0      0      0      9      0      5]
 [     0      0      0      0     12     93      2]
 [     0      0      0      0    183   3435      3]
 [     0      0      0      0   5181   9351     10]
 [     0      0      0      0      0 318103    234]
 [     0      0      0      0      0     12 396568]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       504
           2       0.00      0.00      0.00        14
           3       0.00      0.00      0.00       107
           4       0.00      0.00      0.00      3621
           5       0.96      0.36      0.52     14542
           6       0.96      1.00      0.98    318337
           7       1.00      1.00      1.00    396580

    accuracy                           0.98    733705
   macro avg       0.42      0.34      0.36    733705
weighted avg       0.98      0.98      0.98    733705



In [65]:
# Naive Bayes

In [66]:
nb_clf = NaiveBayes()
nb_clf.fit(train_data,target_features)
predictions_nb = nb_clf.predict(test)

In [67]:
print("Naive Bayes: Attack\n")
print(confusion_matrix(test_labels['attack'],predictions_nb['attack']))
print(classification_report(test_labels['attack'],predictions_nb['attack']))

Naive Bayes: Attack

[[    96     11]
 [  2775 730823]]
              precision    recall  f1-score   support

           0       0.03      0.90      0.06       107
           1       1.00      1.00      1.00    733598

    accuracy                           1.00    733705
   macro avg       0.52      0.95      0.53    733705
weighted avg       1.00      1.00      1.00    733705



In [68]:
print("Naive Bayes: Category\n")
print(confusion_matrix(test_labels['category'],predictions_nb['category']),"\n")
print(classification_report(test_labels['category'],predictions_nb['category']))

Naive Bayes: Category

[[368894  16264     31    120      0]
 [182703 146381    699    329      0]
 [     0      9     96      2      0]
 [ 10751   1630   2040   3742      0]
 [     0      1      5      0      8]] 

              precision    recall  f1-score   support

           0       0.66      0.96      0.78    385309
           1       0.89      0.44      0.59    330112
           2       0.03      0.90      0.06       107
           3       0.89      0.21      0.33     18163
           4       1.00      0.57      0.73        14

    accuracy                           0.71    733705
   macro avg       0.69      0.62      0.50    733705
weighted avg       0.77      0.71      0.68    733705



In [69]:
print("Naive Bayes: Subcategory\n")
print(confusion_matrix(test_labels['subcategory'],predictions_nb['subcategory']))
print(classification_report(test_labels['subcategory'],predictions_nb['subcategory']))

Naive Bayes: Subcategory

[[     0      0      0      0      0      0      0      0]
 [     0    337      0      7      0    146     14      0]
 [     1      0      7      5      0      0      1      0]
 [     0      0      0     96      1      1      9      0]
 [     0    199      0    128      0    151   3143      0]
 [     0    578      0   1912    612   2979   8461      0]
 [     0    815      0    715      5    296 316506      0]
 [     0      0      0      8      2      0     23 396547]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.17      0.67      0.28       504
           2       1.00      0.50      0.67        14
           3       0.03      0.90      0.06       107
           4       0.00      0.00      0.00      3621
           5       0.83      0.20      0.33     14542
           6       0.96      0.99      0.98    318337
           7       1.00      1.00      1.00    396580

    accuracy 

In [70]:
# Decision Tree (Information Gain)

In [71]:
dtree_ig_clf = DecisionTree('entropy')
dtree_ig_clf.fit(train_data,target_features)
predictions_ig = dtree_ig_clf.predict(test)

In [72]:
print("Decision Tree (Information Gain): Attack\n")
print(confusion_matrix(test_labels['attack'],predictions_ig['attack']),"\n")
print(classification_report(test_labels['attack'],predictions_ig['attack']))

Decision Tree (Information Gain): Attack

[[    40     67]
 [     2 733596]] 

              precision    recall  f1-score   support

           0       0.95      0.37      0.54       107
           1       1.00      1.00      1.00    733598

    accuracy                           1.00    733705
   macro avg       0.98      0.69      0.77    733705
weighted avg       1.00      1.00      1.00    733705



In [73]:
print("Decision Tree (Information Gain): Category\n")
print(confusion_matrix(test_labels['category'],predictions_ig['category']))
print(classification_report(test_labels['category'],predictions_ig['category']))

Decision Tree (Information Gain): Category

[[339497  45290      0    522      0]
 [ 11703 318367      0     42      0]
 [     9     15     33     50      0]
 [   351   7450      2  10360      0]
 [     0      0      0     14      0]]
              precision    recall  f1-score   support

           0       0.97      0.88      0.92    385309
           1       0.86      0.96      0.91    330112
           2       0.94      0.31      0.46       107
           3       0.94      0.57      0.71     18163
           4       0.00      0.00      0.00        14

    accuracy                           0.91    733705
   macro avg       0.74      0.54      0.60    733705
weighted avg       0.92      0.91      0.91    733705



In [74]:
print("Decision Tree (Information Gain): Subcategory\n")
print(confusion_matrix(test_labels['subcategory'],predictions_ig['subcategory']),"\n")
print(classification_report(test_labels['subcategory'],predictions_ig['subcategory']))

Decision Tree (Information Gain): Subcategory

[[   384      0      0      0     87     33      0]
 [     0      5      0      0      9      0      0]
 [     0      0     38      4     44      9     12]
 [     0      0      2    942    574   2089     14]
 [    27      0      0    222   8623   5654     16]
 [    23      0      0      0    453 317861      0]
 [     0      0     24      0      0      8 396548]] 

              precision    recall  f1-score   support

           1       0.88      0.76      0.82       504
           2       1.00      0.36      0.53        14
           3       0.59      0.36      0.44       107
           4       0.81      0.26      0.39      3621
           5       0.88      0.59      0.71     14542
           6       0.98      1.00      0.99    318337
           7       1.00      1.00      1.00    396580

    accuracy                           0.99    733705
   macro avg       0.88      0.62      0.70    733705
weighted avg       0.99      0.99      0.99 

In [75]:
# Decision Tree (Gini Index)

In [76]:
dtree_gi_clf = DecisionTree('gini')
dtree_gi_clf.fit(train_data,target_features)
predictions_gi = dtree_gi_clf.predict(test)

In [77]:
print("Decision Tree (Gini Index): Attack\n")
print(confusion_matrix(test_labels['attack'],predictions_gi['attack']),"\n")
print(classification_report(test_labels['attack'],predictions_gi['attack']))

Decision Tree (Gini Index): Attack

[[    39     68]
 [     3 733595]] 

              precision    recall  f1-score   support

           0       0.93      0.36      0.52       107
           1       1.00      1.00      1.00    733598

    accuracy                           1.00    733705
   macro avg       0.96      0.68      0.76    733705
weighted avg       1.00      1.00      1.00    733705



In [78]:
print("Decision Tree (Gini Index): Category\n")
print(confusion_matrix(test_labels['category'],predictions_gi['category']))
print(classification_report(test_labels['category'],predictions_gi['category']))

Decision Tree (Gini Index): Category

[[338396  46453      0    460      0]
 [  8631 321472      1      8      0]
 [     0     18     33     56      0]
 [    68   7383      2  10710      0]
 [     0      5      0      9      0]]
              precision    recall  f1-score   support

           0       0.97      0.88      0.92    385309
           1       0.86      0.97      0.91    330112
           2       0.92      0.31      0.46       107
           3       0.95      0.59      0.73     18163
           4       0.00      0.00      0.00        14

    accuracy                           0.91    733705
   macro avg       0.74      0.55      0.61    733705
weighted avg       0.92      0.91      0.91    733705



In [79]:
print("Decision Tree (Gini Index): Subcategory\n")
print(confusion_matrix(test_labels['subcategory'],predictions_gi['subcategory']),"\n")
print(classification_report(test_labels['subcategory'],predictions_gi['subcategory']))

Decision Tree (Gini Index): Subcategory

[[   416      0      0      0     10     78      0]
 [     0      5      0      0      9      0      0]
 [     1      0     17      5     82      2      0]
 [    10      0      5    860    710   2036      0]
 [     6      3      5     71   9069   5387      1]
 [    63      0      0      0    459 317814      1]
 [     0      0      0      0      0      9 396571]] 

              precision    recall  f1-score   support

           1       0.84      0.83      0.83       504
           2       0.62      0.36      0.45        14
           3       0.63      0.16      0.25       107
           4       0.92      0.24      0.38      3621
           5       0.88      0.62      0.73     14542
           6       0.98      1.00      0.99    318337
           7       1.00      1.00      1.00    396580

    accuracy                           0.99    733705
   macro avg       0.84      0.60      0.66    733705
weighted avg       0.99      0.99      0.99    733

In [80]:
# Gradient Boost

In [81]:
xgb_clf = GradientBoost()
xgb_clf.fit(train_data,target_features)
predictions_gb = xgb_clf.predict(test)

[14:18:14] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[14:19:49] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[14:26:50] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [82]:
print("Gradient Boost: Attack\n")
print(confusion_matrix(test_labels['attack'],predictions_gb['attack']),"\n")
print(classification_report(test_labels['attack'],predictions_gb['attack']))

Gradient Boost: Attack

[[   100      7]
 [     1 733597]] 

              precision    recall  f1-score   support

           0       0.99      0.93      0.96       107
           1       1.00      1.00      1.00    733598

    accuracy                           1.00    733705
   macro avg       1.00      0.97      0.98    733705
weighted avg       1.00      1.00      1.00    733705



In [83]:
print("Gradient Boost: Category\n")
print(confusion_matrix(test_labels['category'],predictions_gb['category']),"\n")
print(classification_report(test_labels['category'],predictions_gb['category']))

Gradient Boost: Category

[[385296     12      0      1      0]
 [    17 330094      1      0      0]
 [     0      0    100      7      0]
 [     0      1      0  18162      0]
 [     0      0      0      0     14]] 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    385309
           1       1.00      1.00      1.00    330112
           2       0.99      0.93      0.96       107
           3       1.00      1.00      1.00     18163
           4       1.00      1.00      1.00        14

    accuracy                           1.00    733705
   macro avg       1.00      0.99      0.99    733705
weighted avg       1.00      1.00      1.00    733705



In [84]:
print("Gradient Boost: Subcategory\n")
print(confusion_matrix(test_labels['subcategory'],predictions_gb['subcategory']),"\n")
print(classification_report(test_labels['subcategory'],predictions_gb['subcategory']))

Gradient Boost: Subcategory

[[   496      0      1      0      1      6      0]
 [     0     14      0      0      0      0      0]
 [     0      0    100      0      7      0      0]
 [     0      0      0   3350    271      0      0]
 [     1      0      0    227  14314      0      0]
 [     0      0      0      0      0 318337      0]
 [     1      0      0      0      0      5 396574]] 

              precision    recall  f1-score   support

           1       1.00      0.98      0.99       504
           2       1.00      1.00      1.00        14
           3       0.99      0.93      0.96       107
           4       0.94      0.93      0.93      3621
           5       0.98      0.98      0.98     14542
           6       1.00      1.00      1.00    318337
           7       1.00      1.00      1.00    396580

    accuracy                           1.00    733705
   macro avg       0.99      0.98      0.98    733705
weighted avg       1.00      1.00      1.00    733705

